const translations = {
  pt: {
    badge: "Desenvolvedor & Tradutor Técnico",
    title_pre: "Automação inteligente, emulação e ",
    title_grad: "soluções open source",
    title_pos: ".",
    subtitle: "Criador da <strong>Suite-Emuladores</strong> e da suíte <strong>PSBBN Translator</strong>. Ferramentas gratuitas projetadas com precisão para facilitar a vida de gamers e entusiastas da tecnologia.",
    btn_explore: "Explorar Projetos",
    btn_discord: "Entrar no Discord Oficial",
    btn_github: "GitHub",
    stat_emulators: "Emuladores Suportados",
    stat_languages: "Idiomas Globais (PSBBN)",
    stat_opensource: "Gratuito & Código Aberto",
    nav_projects: "Projetos",
    nav_about: "Sobre",
    nav_community: "Comunidade",
    sec_projects_title: "Projetos em Destaque",
    sec_projects_sub: "Conheça as principais ferramentas desenvolvidas e mantidas por Emerson Teles.",
    tag_flagship: "Carro-chefe",
    tag_ps2: "Destaque PS2",
    btn_view_github: "Ver no GitHub",
    btn_join_community: "Entrar na Comunidade",
    suite_desc: "Suíte inteligente em PowerShell para download e atualização autônoma de 56 emuladores e frontends. Suporte multilíngue nativo para 10 idiomas.",
    psbbn_desc: "Suíte completa de tradução para o sistema operacional PlayStation Broadband Navigator (PS2). Tradução oficial para PT-BR e automação para mais de 40 idiomas.",
    vault_desc: "Backup portátil e restauração cirúrgica de históricos de conversas de 20 IAs agênticas e ferramentas avançadas de desenvolvimento.",
    roccat_desc: "Suíte de estabilização de áudio, watchdog automático e blindagem contra perdas de sinal para o headset sem fio Roccat Syn Pro Air.",
    photos_desc: "Solução avançada em PowerShell e C# para restauração da rota de abertura rápida e definição de plano de fundo no app Fotos do Windows.",
    discord_card_title: "Comunidade & Suporte",
    discord_card_desc: "Entre no servidor oficial de Emerson Teles no Discord. Tire dúvidas, participe de testes beta e mande sugestões de novas funções.",
    pill_247: "24/7 Ativo",
    pill_bilingual: "Bilíngue",
    pill_windows: "Windows",
    pill_engines: "56 Motores",
    pill_languages: "10 Idiomas",
    pill_ps2_lang: "40 Idiomas",
    pill_portability: "Portabilidade",
    sec_about_title: "Sobre o Desenvolvedor",
    about_p1: "Olá! Sou <strong>Emerson Teles</strong> (conhecido na comunidade de desenvolvimento e mods como <strong>Emertels</strong>).",
    about_p2: "Sempre fui apaixonado por informática, manutenção de sistemas e pela cultura gamer retrô e moderna. Minha missão é criar ferramentas autônomas que economizem tempo e facilitem a vida de quem joga ou trabalha no computador.",
    about_p3: "Além das automações, atuo na <strong>localização técnica e tradução oficial de softwares</strong> e projetos célebres para o Português do Brasil (PT-BR), como o <strong>PSBBN Definitive Project</strong>, utilitários de controle como o <strong>DSX (DualSense X)</strong>, além de jogos como a saga <strong>Silent Hill</strong>.",
    sec_social_title: "Canais & Redes Oficiais",
    sec_social_sub: "Conecte-se comigo e faça parte das nossas comunidades.",
    footer_copy: "© 2026 <strong>Emerson Teles</strong> (@Emertels). Todos os direitos reservados.",
    footer_sub: "Hospedado gratuitamente e com código aberto via GitHub Pages."
  },
  en: {
    badge: "Developer & Technical Translator",
    title_pre: "Intelligent automation, emulation & ",
    title_grad: "open source solutions",
    title_pos: ".",
    subtitle: "Creator of <strong>Suite-Emuladores</strong> and the <strong>PSBBN Translator</strong> suite. High-precision free tools designed to streamline gaming and tech setups.",
    btn_explore: "Explore Projects",
    btn_discord: "Join Official Discord",
    btn_github: "GitHub",
    stat_emulators: "Supported Emulators",
    stat_languages: "Global Languages (PSBBN)",
    stat_opensource: "Free & Open Source",
    nav_projects: "Projects",
    nav_about: "About",
    nav_community: "Community",
    sec_projects_title: "Featured Projects",
    sec_projects_sub: "Discover the main tools built and maintained by Emerson Teles.",
    tag_flagship: "Flagship",
    tag_ps2: "PS2 Spotlight",
    btn_view_github: "View on GitHub",
    btn_join_community: "Join Community",
    suite_desc: "Intelligent PowerShell automation suite for unattended download and updates across 56 emulators and frontends. Native support for 10 languages.",
    psbbn_desc: "Comprehensive translation suite for the PS2 PlayStation Broadband Navigator OS. Official PT-BR localization and 40+ language automation.",
    vault_desc: "Portable backup and precision recovery for local chats across 20 agentic AI assistants and coding environments.",
    roccat_desc: "Complete audio stabilization suite, auto-watchdog and signal drop shield for the Roccat Syn Pro Air wireless headset.",
    photos_desc: "Advanced PowerShell and C# fix restoring fast launch routes and desktop wallpaper setting for Windows Photos app.",
    discord_card_title: "Community & Support",
    discord_card_desc: "Join Emerson Teles' official Discord server. Get help, test beta builds, and suggest new features directly.",
    pill_247: "24/7 Active",
    pill_bilingual: "Bilingual",
    pill_windows: "Windows",
    pill_engines: "56 Engines",
    pill_languages: "10 Languages",
    pill_ps2_lang: "40 Languages",
    pill_portability: "Portability",
    sec_about_title: "About the Developer",
    about_p1: "Hi! I am <strong>Emerson Teles</strong> (known across dev and mod communities as <strong>Emertels</strong>).",
    about_p2: "Passionate about computer science, system administration, and retro/modern gaming. My mission is to build autonomous tools that save time and optimize digital environments.",
    about_p3: "Beyond automation, I specialize in <strong>technical localization and official translations</strong> for Brazilian Portuguese (PT-BR), including the <strong>PSBBN Definitive Project</strong>, controller utilities like <strong>DSX (DualSense X)</strong>, and games like the <strong>Silent Hill</strong> franchise.",
    sec_social_title: "Official Channels & Links",
    sec_social_sub: "Connect with me and be part of our global community.",
    footer_copy: "© 2026 <strong>Emerson Teles</strong> (@Emertels). All rights reserved.",
    footer_sub: "Hosted for free and open source via GitHub Pages."
  },
  es: {
    badge: "Desarrollador y Traductor Técnico",
    title_pre: "Automatización inteligente, emulación y ",
    title_grad: "soluciones de código abierto",
    title_pos: ".",
    subtitle: "Creador de <strong>Suite-Emuladores</strong> y <strong>PSBBN Translator</strong>. Herramientas gratuitas diseñadas para gamers y entusiastas de la tecnología.",
    btn_explore: "Explorar Proyectos",
    btn_discord: "Unirse al Discord Oficial",
    btn_github: "GitHub",
    stat_emulators: "Emuladores Compatibles",
    stat_languages: "Idiomas Globales (PSBBN)",
    stat_opensource: "Gratis y Código Abierto",
    nav_projects: "Proyectos",
    nav_about: "Sobre mí",
    nav_community: "Comunidad",
    sec_projects_title: "Proyectos Destacados",
    sec_projects_sub: "Conozca las principales herramientas desarrolladas por Emerson Teles.",
    tag_flagship: "Principal",
    tag_ps2: "Destacado PS2",
    btn_view_github: "Ver en GitHub",
    btn_join_community: "Unirse a la Comunidad",
    suite_desc: "Suite inteligente en PowerShell para descarga y actualización automática de 56 emuladores y frontends.",
    psbbn_desc: "Suite completa de traducción para PlayStation Broadband Navigator (PS2). Traducción oficial PT-BR y más de 40 idiomas.",
    vault_desc: "Copia de seguridad portátil y recuperación para 20 IAs agénticas y herramientas de programación.",
    roccat_desc: "Estabilización de audio y protección de señal para auriculares Roccat Syn Pro Air.",
    photos_desc: "Corrección avanzada en PowerShell y C# para la aplicación Fotos de Windows.",
    discord_card_title: "Comunidad y Soporte",
    discord_card_desc: "Únete al servidor oficial en Discord para soporte, pruebas beta y sugerencias.",
    pill_247: "24/7 Activo",
    pill_bilingual: "Bilingüe",
    pill_windows: "Windows",
    pill_engines: "56 Motores",
    pill_languages: "10 Idiomas",
    pill_ps2_lang: "40 Idiomas",
    pill_portability: "Portabilidad",
    sec_about_title: "Sobre el Desarrollador",
    about_p1: "¡Hola! Soy <strong>Emerson Teles</strong> (@Emertels).",
    about_p2: "Apasionado por la tecnología, los videojuegos y la automatización que ahorra tiempo a los usuarios.",
    about_p3: "Especialista en <strong>localizaciones técnicas</strong> como el PSBBN Definitive Project, DSX y la saga Silent Hill.",
    sec_social_title: "Canales y Redes Oficiales",
    sec_social_sub: "Conéctate conmigo en todas las plataformas.",
    footer_copy: "© 2026 <strong>Emerson Teles</strong> (@Emertels). Todos los derechos reservados.",
    footer_sub: "Alojado de forma gratuita mediante GitHub Pages."
  },
  fr: {
    badge: "Développeur & Traducteur Technique",
    title_pre: "Automatisation intelligente, émulation & ",
    title_grad: "solutions open source",
    title_pos: ".",
    subtitle: "Créateur de <strong>Suite-Emuladores</strong> et de la suite <strong>PSBBN Translator</strong>. Des outils gratuits haute précision pour les gamers.",
    btn_explore: "Explorer les Projets",
    btn_discord: "Rejoindre le Discord Officiel",
    btn_github: "GitHub",
    stat_emulators: "Émulateurs Supportés",
    stat_languages: "Langues Globales (PSBBN)",
    stat_opensource: "Gratuit & Open Source",
    nav_projects: "Projets",
    nav_about: "À propos",
    nav_community: "Communauté",
    sec_projects_title: "Projets à la Une",
    sec_projects_sub: "Découvrez les principaux outils créés par Emerson Teles.",
    tag_flagship: "Phare",
    tag_ps2: "Vedette PS2",
    btn_view_github: "Voir sur GitHub",
    btn_join_community: "Rejoindre la Communauté",
    suite_desc: "Suite PowerShell d'automatisation pour le téléchargement et la mise à jour de 56 émulateurs.",
    psbbn_desc: "Suite de traduction pour le système PS2 PSBBN. Traduction officielle PT-BR et plus de 40 langues.",
    vault_desc: "Sauvegarde et restauration de discussions pour 20 IA et outils de dev.",
    roccat_desc: "Stabilisation audio sans fil pour le casque Roccat Syn Pro Air.",
    photos_desc: "Correctif Windows Photos développé en PowerShell et C#.",
    discord_card_title: "Communauté & Support",
    discord_card_desc: "Rejoignez le Discord officiel pour de l'aide et des versions de test.",
    pill_247: "24/7 Actif",
    pill_bilingual: "Bilingue",
    pill_windows: "Windows",
    pill_engines: "56 Moteurs",
    pill_languages: "10 Langues",
    pill_ps2_lang: "40 Langues",
    pill_portability: "Portabilité",
    sec_about_title: "À propos du Développeur",
    about_p1: "Bonjour ! Je suis <strong>Emerson Teles</strong> (@Emertels).",
    about_p2: "Passionné d'informatique, de rétrogaming et d'automatisation logicielle.",
    about_p3: "Spécialiste de la <strong>localisation technique</strong> (PSBBN, DSX, Silent Hill).",
    sec_social_title: "Réseaux & Liens Officiels",
    sec_social_sub: "Rejoignez-moi sur toutes les plateformes.",
    footer_copy: "© 2026 <strong>Emerson Teles</strong> (@Emertels). Tous droits réservés.",
    footer_sub: "Hébergé gratuitement via GitHub Pages."
  },
  de: {
    badge: "Entwickler & Technischer Übersetzer",
    title_pre: "Intelligente Automatisierung, Emulation & ",
    title_grad: "Open-Source-Lösungen",
    title_pos: ".",
    subtitle: "Entwickler von <strong>Suite-Emuladores</strong> und <strong>PSBBN Translator</strong>. Kostenlose Tools für Gamer und Tech-Enthusiasten.",
    btn_explore: "Projekte Erkunden",
    btn_discord: "Offiziellem Discord Beitreten",
    btn_github: "GitHub",
    stat_emulators: "Unterstützte Emulatoren",
    stat_languages: "Globale Sprachen (PSBBN)",
    stat_opensource: "Kostenlos & Open Source",
    nav_projects: "Projekte",
    nav_about: "Über mich",
    nav_community: "Community",
    sec_projects_title: "Ausgewählte Projekte",
    sec_projects_sub: "Entdecken Sie die Werkzeuge von Emerson Teles.",
    tag_flagship: "Hauptprojekt",
    tag_ps2: "PS2 Highlight",
    btn_view_github: "Auf GitHub ansehen",
    btn_join_community: "Community beitreten",
    suite_desc: "PowerShell-Suite für automatische Downloads und Updates von 56 Emulatoren.",
    psbbn_desc: "Übersetzungssuite für das PS2 PSBBN-System mit Unterstützung für 40+ Sprachen.",
    vault_desc: "Portables Backup für Konversationen von 20 KI-Agenten.",
    roccat_desc: "Audio-Stabilisierung und Signalüberwachung für Roccat Syn Pro Air.",
    photos_desc: "Erweiterter Fix für die Windows-Fotos-App in PowerShell und C#.",
    discord_card_title: "Community & Support",
    discord_card_desc: "Treten Sie dem offiziellen Discord für Beta-Tests und Feedback bei.",
    pill_247: "24/7 Aktiv",
    pill_bilingual: "Zweisprachig",
    pill_windows: "Windows",
    pill_engines: "56 Engines",
    pill_languages: "10 Sprachen",
    pill_ps2_lang: "40 Sprachen",
    pill_portability: "Portabilität",
    sec_about_title: "Über den Entwickler",
    about_p1: "Hallo! Ich bin <strong>Emerson Teles</strong> (@Emertels).",
    about_p2: "Begeistert von Retro-Gaming, Systemadministration und Automatisierung.",
    about_p3: "Experte für <strong>technische Lokalisierung</strong> (PSBBN, DSX, Silent Hill).",
    sec_social_title: "Offizielle Kanäle",
    sec_social_sub: "Verbinden Sie sich mit mir auf allen Plattformen.",
    footer_copy: "© 2026 <strong>Emerson Teles</strong> (@Emertels). Alle Rechte vorbehalten.",
    footer_sub: "Kostenlos gehostet über GitHub Pages."
  },
  it: {
    badge: "Sviluppatore e Traduttore Tecnico",
    title_pre: "Automazione intelligente, emulazione e ",
    title_grad: "soluzioni open source",
    title_pos: ".",
    subtitle: "Creatore di <strong>Suite-Emuladores</strong> e <strong>PSBBN Translator</strong>. Strumenti gratuiti ad alta precisione per gamer.",
    btn_explore: "Esplora i Progetti",
    btn_discord: "Unisciti al Discord Ufficiale",
    btn_github: "GitHub",
    stat_emulators: "Emulatori Supportati",
    stat_languages: "Lingue Globali (PSBBN)",
    stat_opensource: "Gratuito e Open Source",
    nav_projects: "Progetti",
    nav_about: "Chi sono",
    nav_community: "Community",
    sec_projects_title: "Progetti in Evidenza",
    sec_projects_sub: "Scopri gli strumenti realizzati da Emerson Teles.",
    tag_flagship: "Principale",
    tag_ps2: "In Primo Piano PS2",
    btn_view_github: "Vedi su GitHub",
    btn_join_community: "Unisciti alla Community",
    suite_desc: "Suite di automazione PowerShell per scaricare e aggiornare 56 emulatori.",
    psbbn_desc: "Suite di traduzione per il sistema operativo PS2 PSBBN con oltre 40 lingue.",
    vault_desc: "Backup portatile e ripristino per 20 assistenti IA.",
    roccat_desc: "Stabilizzazione audio e watchdog per cuffie Roccat Syn Pro Air.",
    photos_desc: "Correzione avanzata in PowerShell e C# per l'app Foto di Windows.",
    discord_card_title: "Community e Supporto",
    discord_card_desc: "Entra nel server Discord ufficiale per supporto e test beta.",
    pill_247: "24/7 Attivo",
    pill_bilingual: "Bilingue",
    pill_windows: "Windows",
    pill_engines: "56 Motori",
    pill_languages: "10 Lingue",
    pill_ps2_lang: "40 Lingue",
    pill_portability: "Portabilità",
    sec_about_title: "Informazioni sullo Sviluppatore",
    about_p1: "Ciao! Sono <strong>Emerson Teles</strong> (@Emertels).",
    about_p2: "Appassionato di informatica, retrogaming e automazione software.",
    about_p3: "Specialista in <strong>localizzazione tecnica</strong> (PSBBN, DSX, Silent Hill).",
    sec_social_title: "Canali e Link Ufficiali",
    sec_social_sub: "Rimani in contatto su tutte le piattaforme.",
    footer_copy: "© 2026 <strong>Emerson Teles</strong> (@Emertels). Tutti i diritti riservati.",
    footer_sub: "Ospitato gratuitamente tramite GitHub Pages."
  },
  ja: {
    badge: "開発者 & テクニカル翻訳者",
    title_pre: "高度な自動化、エミュレーション、そして",
    title_grad: "オープンソースソリューション",
    title_pos: "。",
    subtitle: "<strong>Suite-Emuladores</strong> および <strong>PSBBN Translator</strong> の開発者。ゲーマーとPCユーザーのための高性能無料ツールを提供。",
    btn_explore: "プロジェクトを見る",
    btn_discord: "公式Discordに参加",
    btn_github: "GitHub",
    stat_emulators: "対応エミュレータ数",
    stat_languages: "対応言語数 (PSBBN)",
    stat_opensource: "完全無料 & オープンソース",
    nav_projects: "プロジェクト",
    nav_about: "概要",
    nav_community: "コミュニティ",
    sec_projects_title: "注目プロジェクト",
    sec_projects_sub: "Emerson Teles が開発・保守している主要プロジェクト。",
    tag_flagship: "代表作",
    tag_ps2: "PS2注目作",
    btn_view_github: "GitHubで見る",
    btn_join_community: "コミュニティに参加",
    suite_desc: "56種類のエミュレータとフロントエンドを自律的にダウンロード・更新するPowerShell自動化スイート。",
    psbbn_desc: "PS2用OS「PlayStation Broadband Navigator」向け総合翻訳スイート。40以上の言語に対応。",
    vault_desc: "20種の開発系AIおよびコーディングツールのチャット履歴を保護するポータブルバックアップ。",
    roccat_desc: "Roccat Syn Pro Air ワイヤレスヘッドセットのオーディオ安定化＆自動監視ガード。",
    photos_desc: "Windowsフォトアプリの高速起動と壁紙設定を修復するPowerShell/C#ソリューション。",
    discord_card_title: "コミュニティ＆サポート",
    discord_card_desc: "公式Discordサーバーでサポート、ベータテスト、機能提案を受け付けています。",
    pill_247: "24時間稼働",
    pill_bilingual: "多言語対応",
    pill_windows: "Windows",
    pill_engines: "56エンジン",
    pill_languages: "10言語",
    pill_ps2_lang: "40言語",
    pill_portability: "高ポータブル",
    sec_about_title: "開発者について",
    about_p1: "こんにちは！ <strong>Emerson Teles</strong>（コミュニティ名：<strong>Emertels</strong>）です。",
    about_p2: "IT、レトロゲーム、PC自動化に情熱を注ぎ、ユーザーの時間を節約するツールを開発しています。",
    about_p3: "PSBBN、DSX、サイレントヒルシリーズなど、多数の<strong>技術翻訳・ローカライズ</strong>も手掛けています。",
    sec_social_title: "公式リンク & チャンネル",
    sec_social_sub: "コミュニティと各種SNSで繋がりましょう。",
    footer_copy: "© 2026 <strong>Emerson Teles</strong> (@Emertels). All rights reserved.",
    footer_sub: "GitHub Pages にて無料ホスティング中。"
  },
  zh: {
    badge: "开发者 & 技术本地化翻译者",
    title_pre: "智能自动化、模拟器以及",
    title_grad: "开源解决方案",
    title_pos: "。",
    subtitle: "<strong>Suite-Emuladores</strong> 与 <strong>PSBBN Translator</strong> 套件的创作者。专为游戏玩家与技术爱好者打造的免费高精度工具。",
    btn_explore: "浏览项目",
    btn_discord: "加入官方Discord",
    btn_github: "GitHub",
    stat_emulators: "支持的模拟器",
    stat_languages: "全局支持语言 (PSBBN)",
    stat_opensource: "100% 免费与开源",
    nav_projects: "项目",
    nav_about: "关于",
    nav_community: "社区",
    sec_projects_title: "精选项目",
    sec_projects_sub: "探索 Emerson Teles 独立打造与维护的核心工具。",
    tag_flagship: "旗舰项目",
    tag_ps2: "PS2 特别推荐",
    btn_view_github: "前往 GitHub",
    btn_join_community: "加入社区",
    suite_desc: "基于PowerShell的智能套件，支持56款模拟器及前端的自动化下载与更新。",
    psbbn_desc: "适用于PS2宽带导航系统的多语言翻译套件，支持40余种语言及官方巴西葡萄牙语本地化。",
    vault_desc: "适用于20款智能体AI工具与编程助手的本地对话便携备份与恢复方案。",
    roccat_desc: "针对 Roccat Syn Pro Air 无线耳机的音频稳定与掉线防护程序。",
    photos_desc: "利用 PowerShell 与 C# 修复 Windows 照片应用快速启动与壁纸设置的工具。",
    discord_card_title: "社区与技术支持",
    discord_card_desc: "加入官方 Discord 服务器获取帮助、参与测试并提交反馈。",
    pill_247: "全天候在线",
    pill_bilingual: "双语服务",
    pill_windows: "Windows",
    pill_engines: "56款引擎",
    pill_languages: "10种语言",
    pill_ps2_lang: "40种语言",
    pill_portability: "便携安全",
    sec_about_title: "关于开发者",
    about_p1: "你好！我是 <strong>Emerson Teles</strong>（开源社区称 <strong>Emertels</strong>）。",
    about_p2: "热爱计算机系统维护、复古与现代游戏，致力于打造节省时间的自动化工具。",
    about_p3: "同时主导多项<strong>技术本地化翻译</strong>工作（如 PSBBN、DSX、寂静岭系列等）。",
    sec_social_title: "官方频道与社交主页",
    sec_social_sub: "欢迎在各大平台与我取得联系。",
    footer_copy: "© 2026 <strong>Emerson Teles</strong> (@Emertels). 保留所有权利。",
    footer_sub: "基于 GitHub Pages 免费部署与托管。"
  },
  ru: {
    badge: "Разработчик и Технический Переводчик",
    title_pre: "Умная автоматизация, эмуляция и ",
    title_grad: "open-source решения",
    title_pos: ".",
    subtitle: "Создатель <strong>Suite-Emuladores</strong> и <strong>PSBBN Translator</strong>. Бесплатные инструменты для геймеров и энтузиастов.",
    btn_explore: "Смотреть Проекты",
    btn_discord: "Официальный Discord",
    btn_github: "GitHub",
    stat_emulators: "Эмуляторов Поддерживается",
    stat_languages: "Языков Мира (PSBBN)",
    stat_opensource: "Бесплатно и Open Source",
    nav_projects: "Проекты",
    nav_about: "Обо мне",
    nav_community: "Сообщество",
    sec_projects_title: "Избранные Проекты",
    sec_projects_sub: "Основные программы, созданные и поддерживаемые Emerson Teles.",
    tag_flagship: "Флагман",
    tag_ps2: "Для PS2",
    btn_view_github: "Открыть на GitHub",
    btn_join_community: "В Сообщество",
    suite_desc: "PowerShell-комплекс для автоматической загрузки и обновления 56 эмуляторов.",
    psbbn_desc: "Полный комплект локализации для ОС PS2 PSBBN с поддержкой 40+ языков.",
    vault_desc: "Портативное резервное копирование переписок для 20 ИИ-ассистентов.",
    roccat_desc: "Стабилизация звука и сторожевой таймер для гарнитуры Roccat Syn Pro Air.",
    photos_desc: "Решение на PowerShell и C# для исправления приложения 'Фотографии Windows'.",
    discord_card_title: "Сообщество и Поддержка",
    discord_card_desc: "Присоединяйтесь к официальному Discord-серверу для общения и помощи.",
    pill_247: "24/7 Актив",
    pill_bilingual: "Двуязычный",
    pill_windows: "Windows",
    pill_engines: "56 Моторов",
    pill_languages: "10 Языков",
    pill_ps2_lang: "40 Языков",
    pill_portability: "Портативность",
    sec_about_title: "Об Авторе",
    about_p1: "Привет! Я <strong>Emerson Teles</strong> (@Emertels).",
    about_p2: "Увлекаюсь системным администрированием, ретро-играми и умной автоматизацией.",
    about_p3: "Автор <strong>официальных технических переводов</strong> (PSBBN, DSX, Silent Hill).",
    sec_social_title: "Официальные Ссылки",
    sec_social_sub: "Присоединяйтесь на всех доступных площадках.",
    footer_copy: "© 2026 <strong>Emerson Teles</strong> (@Emertels). Все права защищены.",
    footer_sub: "Бесплатный хостинг на GitHub Pages."
  },
  ko: {
    badge: "개발자 & 기술 번역가",
    title_pre: "스마트한 자동화, 에뮬레이션 그리고 ",
    title_grad: "오픈소스 솔루션",
    title_pos: ".",
    subtitle: "<strong>Suite-Emuladores</strong> 및 <strong>PSBBN Translator</strong> 제작자. 게이머와 PC 사용자를 위해 정밀하게 설계된 무료 도구.",
    btn_explore: "프로젝트 둘러보기",
    btn_discord: "공식 디스코드 참여",
    btn_github: "GitHub",
    stat_emulators: "지원 에뮬레이터 수",
    stat_languages: "글로벌 지원 언어 (PSBBN)",
    stat_opensource: "100% 무료 & 오픈소스",
    nav_projects: "프로젝트",
    nav_about: "소개",
    nav_community: "커뮤니티",
    sec_projects_title: "주요 프로젝트",
    sec_projects_sub: "Emerson Teles가 개발하고 유지 관리하는 핵심 소프트웨어.",
    tag_flagship: "대표작",
    tag_ps2: "PS2 추천",
    btn_view_github: "GitHub에서 보기",
    btn_join_community: "커뮤니티 참여",
    suite_desc: "56개 에뮬레이터와 프론트엔드를 자동으로 다운로드하고 업데이트하는 PowerShell 스위트.",
    psbbn_desc: "PS2 브로드밴드 내비게이터(PSBBN) OS를 위한 다국어 번역 스위트. 40개 언어 지원.",
    vault_desc: "20개 AI 에이전트 및 코딩 도구의 대화 기록을 안전하게 보관하는 휴대용 백업.",
    roccat_desc: "Roccat Syn Pro Air 무선 헤드셋을 위한 오디오 안정화 및 신호 보호 솔루션.",
    photos_desc: "Windows 사진 앱의 빠른 실행과 배경화면 설정을 복구하는 고급 수정 도구.",
    discord_card_title: "커뮤니티 & 지원",
    discord_card_desc: "공식 디스코드에서 문제 해결 지원과 베타 테스트에 참여해보세요.",
    pill_247: "24/7 상시 운영",
    pill_bilingual: "다국어 지원",
    pill_windows: "Windows",
    pill_engines: "56개 엔진",
    pill_languages: "10개 언어",
    pill_ps2_lang: "40개 언어",
    pill_portability: "우수한 휴대성",
    sec_about_title: "개발자 소개",
    about_p1: "안녕하세요! 개발자이자 번역가인 <strong>Emerson Teles</strong> (@Emertels)입니다.",
    about_p2: "컴퓨터 시스템 관리와 게임 문화에 깊은 열정을 품고 편리한 자동화 도구를 만듭니다.",
    about_p3: "PSBBN, DSX, 사일런트 힐 시리즈 등의 <strong>공식 기술 번역 및 로컬라이제이션</strong>을 진행해왔습니다.",
    sec_social_title: "공식 채널 & 링크",
    sec_social_sub: "공식 소셜 미디어와 커뮤니티에서 함께 소통하세요.",
    footer_copy: "© 2026 <strong>Emerson Teles</strong> (@Emertels). All rights reserved.",
    footer_sub: "GitHub Pages를 통해 무료로 호스팅됩니다."
  }
};

function setLanguage(lang) {
  if (!translations[lang]) lang = 'pt';
  const t = translations[lang];
  
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (t[key]) {
      el.innerHTML = t[key];
    }
  });

  const select = document.getElementById('langSelect');
  if (select && select.value !== lang) {
    select.value = lang;
  }

  localStorage.setItem('preferred_lang', lang);
  document.documentElement.lang = lang;
}

document.addEventListener('DOMContentLoaded', () => {
  const savedLang = localStorage.getItem('preferred_lang');
  if (savedLang && translations[savedLang]) {
    setLanguage(savedLang);
  } else {
    const browserLang = (navigator.language || navigator.userLanguage || 'pt').substring(0, 2).toLowerCase();
    if (translations[browserLang]) {
      setLanguage(browserLang);
    } else {
      setLanguage('pt');
    }
  }

  const select = document.getElementById('langSelect');
  if (select) {
    select.addEventListener('change', (e) => {
      setLanguage(e.target.value);
    });
  }
});
